# coding: utf-8

"""
    Внутренний API для поиска по базе СМИ

    Позволяет искать документы и издания с использованием языка  запроосов public.ru. Не требует авторизации, поэтому должен быть доступен только из внутренней сети.   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.edition_item import EditionItem  # noqa: E501
from swagger_client.rest import ApiException


class TestEditionItem(unittest.TestCase):
    """EditionItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditionItem(self):
        """Test EditionItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.edition_item.EditionItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
