# coding: utf-8

"""
    Внутренний API для поиска по базе СМИ

    Позволяет искать документы и издания с использованием языка  запроосов public.ru. Не требует авторизации, поэтому должен быть доступен только из внутренней сети.   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.doc_api import DocApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocApi(unittest.TestCase):
    """DocApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.doc_api.DocApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_doc_doc_id_get(self):
        """Test case for doc_doc_id_get

        returns a document  # noqa: E501
        """
        pass

    def test_search_documents(self):
        """Test case for search_documents

        searches documents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
