# coding: utf-8

"""
    Public Search API

    Searches documens and editions  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.doc import Doc  # noqa: E501
from swagger_client.rest import ApiException


class TestDoc(unittest.TestCase):
    """Doc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoc(self):
        """Test Doc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.doc.Doc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
