# coding: utf-8

"""
    Public Search API

    Searches documens and editions  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.edition_item import EditionItem  # noqa: F401,E501


class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'int',
        'total': 'int',
        'items': 'list[EditionItem]'
    }

    attribute_map = {
        'time': 'time',
        'total': 'total',
        'items': 'items'
    }

    def __init__(self, time=None, total=None, items=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501

        self._time = None
        self._total = None
        self._items = None
        self.discriminator = None

        if time is not None:
            self.time = time
        if total is not None:
            self.total = total
        if items is not None:
            self.items = items

    @property
    def time(self):
        """Gets the time of this InlineResponse2001.  # noqa: E501


        :return: The time of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this InlineResponse2001.


        :param time: The time of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._time = time

    @property
    def total(self):
        """Gets the total of this InlineResponse2001.  # noqa: E501


        :return: The total of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this InlineResponse2001.


        :param total: The total of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def items(self):
        """Gets the items of this InlineResponse2001.  # noqa: E501


        :return: The items of this InlineResponse2001.  # noqa: E501
        :rtype: list[EditionItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this InlineResponse2001.


        :param items: The items of this InlineResponse2001.  # noqa: E501
        :type: list[EditionItem]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
